# workflow åç§°
name: image-mirror

# å½“æ–°å»º issues æ—¶ï¼Œè§¦å‘
on:
  issues:
    types:
      - opened
      - reopened
      - edited


# éœ€è¦æ‰§è¡Œçš„ä»»åŠ¡åˆ—è¡¨
jobs:
  # é•œåƒè½¬æ¢ä»»åŠ¡
  sync_to_target_registry:
    # è¿è¡Œç¯å¢ƒ
    runs-on: ubuntu-22.04
    # è¿è¡Œæ¡ä»¶ => issues çš„ label åŒ…å« image-mirror
    # if: contains(github.event.issue.labels.*.name, 'image-mirror')
    concurrency:
      group: ${{ github.workflow }}-${{ github.actor }}
      cancel-in-progress: true
    # é•œåƒè½¬æ¢ä»»åŠ¡çš„æ­¥éª¤åˆ—è¡¨
    steps:

      - name: Check out code
        uses: actions/checkout@v2
      # - uses: hmarr/debug-action@v2
      #   name: debug
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check issue body for image format
        id: check_body
        run: |
          python .github/scripts/check_image_format.py "${{ github.event.issue.body }}"

      - name: Add comment if body is not image format
        if: steps.check_body.outputs.is_image_format == 'false'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ github.event.issue.user.login }} 
            !!!è¯·ä½¿ç”¨æ ‡å‡†é•œåƒæ ¼å¼
            1. é•œåƒè¦å¸¦tag,å¦‚nginx,è¯·å†™ä¸ºnginx:latest
            2. æ ‡é¢˜ä¸é‡è¦,issueæè¿°éƒ¨åˆ†,æ¯è¡Œä¸€ä¸ªé•œåƒä¸è¦æœ‰å…¶ä»–å†…å®¹,ä½ å¯ä»¥ç›´æ¥æ›´æ–°ä½ çš„issue
          reactions: hooray
          edit-mode: replace
      - name: Update issue title with image summary
        if: steps.check_body.outputs.is_image_format == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = context.payload.issue.body;

            // ğŸ§¾ æ‹†åˆ† bodyï¼Œå¹¶è·³è¿‡ç¬¬ä¸€è¡Œ
            const lines = body.split(/\r?\n/).map(line => line.trim()).filter(Boolean);
            const images = lines.slice(1); // ä»ç¬¬äºŒè¡Œå¼€å§‹æå–é•œåƒå

            const top3 = images.slice(0, 3).join(' | ');
            const total = images.length;

            const newTitle = `${top3}  (å…± ${total} ä¸ªé•œåƒ)`;

            await github.rest.issues.update({
              owner,
              repo,
              issue_number,
              title: newTitle
            });

      - name: Add image-mirror label if body is image format
        if: steps.check_body.outputs.is_image_format == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'image-mirror'

      - name: Create comment
        if: ${{ steps.check_body.outputs.is_image_format == 'true' && steps.fc.outputs.comment-id == '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Syncing image to TargetRegistry, please wait a moment  
            [Check the progress](https://github.com/${{ github.repository_owner }}/image-mirror/actions/runs/${{ github.run_id }})    
          reactions: rocket

      - name: prepare
        if: steps.check_body.outputs.is_image_format == 'true'
        run: |
          wget -q  https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.4/image-syncer-v1.5.4-linux-amd64.tar.gz
          tar zxf image-syncer-v1.5.4-linux-amd64.tar.gz 
          sudo  apt install dos2unix 
      - name: start sync
        if: steps.check_body.outputs.is_image_format == 'true'
        id: syncImage
        env:
          TARGET_REGISTRY_PASSWORD: ${{ secrets.TARGET_REGISTRY_PASSWORD }}
          TARGET_REGISTRY_USER: ${{ vars.TARGET_REGISTRY_USER }}
          # TARGET_REGISTRY: index.docker.io
          # TARGET_REGISTRY: registry.cn-hangzhou.aliyuncs.com
          TARGET_NAMESPACE: ${{ vars.TARGET_NAMESPACE }}
          TARGET_REGISTRY: ${{ vars.TARGET_REGISTRY }}
        #å¤„ç†bodyä¸­çš„ç©ºæ ¼å’Œtabå’Œæ¢è¡Œï¼Œå¹¶åœ¨ç»“å°¾æ·»åŠ : ï¼Œ å†™å…¥images.yml æ–‡ä»¶
        run: | 
          echo "${{ github.event.issue.body }}" > images-init.yml 
          dos2unix              images-init.yml
          sed -i 's/^[ \t]*//g' images-init.yml
          sed -i 's/[ \t]*$//g' images-init.yml
          sed -i '/^[  ]*$/d'   images-init.yml
          # img=$(cat images-init.yml)
          img=$(tail -n +2 images-init.yml)
          for i in ${img[@]}
          do
            tagName=$(echo $i | awk -F "/" '{print $NF}');
            echo $i: ${TARGET_REGISTRY}/${TARGET_NAMESPACE}/${tagName} >> images.yml;
            echo ${TARGET_REGISTRY}/${TARGET_NAMESPACE}/${tagName} >> dockerhub-image.yml;
          done
          cat images.yml
          ./image-syncer  --auth=./auth.yml --images=./images.yml 
      - name: Add Success Issues
        if: ${{ success() && steps.check_body.outputs.is_image_format == 'true' }} 
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['succeed']
            })

      - id: get-comment-body
        if: steps.check_body.outputs.is_image_format == 'true' 
        run: |
          body="$(cat script.md)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

          dockerhubImage="$(cat dockerhub-image.yml)"
          dockerhubImage="${dockerhubImage//'%'/'%25'}"
          dockerhubImage="${dockerhubImage//$'\n'/'%0A'}"
          dockerhubImage="${dockerhubImage//$'\r'/'%0D'}" 
          echo "::set-output name=dockerhubImage::$dockerhubImage"

          sourceImage="$(cat images-init.yml)"
          sourceImage="${sourceImage//'%'/'%25'}"
          sourceImage="${sourceImage//$'\n'/'%0A'}"
          sourceImage="${sourceImage//$'\r'/'%0D'}" 
          echo "::set-output name=sourceImage::$sourceImage"

      - name: Find Comment
        if: steps.check_body.outputs.is_image_format == 'true'      
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Syncing image to TargetRegistry

      - name: Add Tips
        if: ${{ success() && steps.check_body.outputs.is_image_format == 'true'  }} 
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            [Check the progress](https://github.com/${{ github.repository_owner }}/image-mirror/actions/runs/${{ github.run_id }})              
            ## é•œåƒä¿¡æ¯å¦‚ä¸‹
            - dockerhub-image.yml  
            ```shell
            ${{ steps.get-comment-body.outputs.dockerhubImage }}
            ```
            - images-init.yml
            ```shell
            ${{ steps.get-comment-body.outputs.sourceImage }}
            ```            
            ${{ steps.get-comment-body.outputs.body }}
          reactions: hooray
          edit-mode: replace
      - name: Add failure hint comment
        if: failure() && steps.check_body.outputs.is_image_format == 'true'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            âŒ é•œåƒåŒæ­¥å¤±è´¥ï¼Œè¯·æ£€æŸ¥ä»¥ä¸‹å‡ ç‚¹ï¼š
            - æºé•œåƒæ˜¯å¦æ‹¼å†™é”™è¯¯ï¼Ÿ
            - tag æ˜¯å¦å­˜åœ¨ï¼ˆå¦‚ `latest`ã€`1.21`ï¼‰ï¼Ÿ
            - è¯¥é•œåƒæ˜¯å¦ä¸ºå…¬å¼€å¯æ‹‰å–çš„é•œåƒï¼Ÿ
            - è‹¥ä¸ºç§æœ‰é•œåƒï¼Œè¯·ç¡®è®¤ç›®æ ‡ registry æœ‰è®¿é—®æƒé™

            å¯å‚è€ƒ logsï¼š
            [æŸ¥çœ‹å·¥ä½œè¯¦æƒ…](https://github.com/${{ github.repository_owner }}/image-mirror/actions/runs/${{ github.run_id }})

          reactions: confused

